# -*- coding: utf-8 -*-
"""07_19101050_Sabiha Afrin.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wjUiK3odXfq_tkhsr_iejxQrrLwHPKdX
"""

import pandas as pd
import numpy as np
import sklearn

medical = pd.read_csv('/content/sample_data/Melanoma TFRecords 256x256 (1).csv')
medical.head(33127)

medical.shape

medical.isnull()

medical.isnull().sum()

from sklearn.impute import SimpleImputer
impute = SimpleImputer(missing_values=np.nan, strategy='mean')
impute.fit(medical[['age_approx']])
medical['age_approx'] = impute.transform(medical[['age_approx']])

medical.isnull().sum()

medical.info()

medical['sex'].unique()

from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()
medical['image_name']  = enc.fit_transform(medical['image_name'])
medical['patient_id'] = enc.fit_transform(medical['patient_id'])
medical['sex'] = enc.fit_transform(medical['sex'])
medical['anatom_site_general_challenge'] = enc.fit_transform(medical['anatom_site_general_challenge'])
medical['diagnosis'] = enc.fit_transform(medical['diagnosis'])
medical['benign_malignant'] = enc.fit_transform(medical['benign_malignant'])
medical.info()

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x = medical.values
x_train_scaled = scaler.fit_transform(x)
medical = pd.DataFrame(x_train_scaled)
medical.head(33127)

exo = pd.read_csv('/content/sample_data/Melanoma TFRecords 256x256 (1).csv')

from sklearn.model_selection import train_test_split
features_column = ['image_name', 'patient_id', 'sex', 'age_approx', 'anatom_site_general_challenge', 'diagnosis', 'benign_malignant', 'target', 'tfrecord', 'width', 'height']
label_column = ['patient_code']
features_dataset = pd.DataFrame(exo[features_column])
label_dataset = pd.DataFrame(exo[label_column])
x_Train, x_Test, y_Train, y_Test = train_test_split(features_dataset, label_dataset, test_size = 0.30)
x_Train.head()
x_Test.head()
y_Train.head()
y_Test.head()